# The URL the site will be built for
base_url = "https://0xsooki.github.io/"

# Site title and description
title = "Bence Soóki-Tóth"
description = "MSc student at Aarhus University and researcher at Eötvös Loránd University, working on cryptoeconomics, proof systems, multi-party computation and zero-knowledge."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# Site title displayed in navigation
site_title = "sooki"

# Social media links
social_links = [
    { name = "scholar", url = "https://scholar.google.com/citations?user=pHUa0aQAAAAJ&hl=en&authuser=2" },
    { name = "github", url = "https://github.com/bencesookitoth" },
]

# Last update date
last_update = "17 aug 2026"
